import { useEffect, useState } from 'react';
import * as Clipboard from 'expo-clipboard';
import { Pressable, ScrollView, Switch, Text, TextInput, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { api } from '@/api';
import { AssetIcon, Button, ModePill, Page, SectionHeader } from '@/components';
import { demoTokens } from '@/demo';
import { dark } from '@/theme';

type Settings = { active: boolean; automationMode: 'SIMULATION' | 'MANUAL' | 'SEMI_AUTO' | 'FULL_AUTO'; riskLevel: 'SAFE' | 'BALANCED' | 'SNIPER'; maxTradeNgn: number; takeProfitPercent: number; stopLossPercent: number; dailyLossLimitPercent: number; maxOpenTrades: number; maxSlippagePercent: number; minimumLiquidityNgn: number };
const defaults: Settings = { active: false, automationMode: 'SIMULATION', riskLevel: 'BALANCED', maxTradeNgn: 10000, takeProfitPercent: 30, stopLossPercent: 12, dailyLossLimitPercent: 5, maxOpenTrades: 3, maxSlippagePercent: 1.5, minimumLiquidityNgn: 2000000 };
const logs = [
  { time: '06:41:28', token: 'Naija Frog', signal: 'Runner score 91', score: 91, reason: 'Liquidity healthy · 428 new holders', status: 'WATCH' },
  { time: '06:41:11', token: 'Sabi Cat', signal: 'Whale accumulation', score: 84, reason: '₦3.8M accumulated across 11 buys', status: 'APPROVED' },
  { time: '06:40:52', token: 'Jollof Wars', signal: 'Concentration alert', score: 72, reason: 'Top wallets control 41% of supply', status: 'BLOCKED' },
  { time: '06:40:33', token: 'No Dulling', signal: 'Bonding curve 64%', score: 78, reason: 'Volume accelerating, waiting for holders', status: 'WATCH' }
];
const blocked = [
  { token: 'Jollof Wars', reason: 'Wallet concentration above safe threshold', outcome: 'Down 38% after 10m', quality: 'Good block', color: dark.green },
  { token: 'Lagos Pepe', reason: 'Liquidity below ₦1.2M minimum', outcome: 'Liquidity removed after 6m', quality: 'Rug avoided', color: dark.green },
  { token: 'Sapa Inu', reason: 'Volume pattern looked synthetic', outcome: 'Up 44% then retraced', quality: 'Review rule', color: dark.yellow }
];
const missed = [
  { token: 'Area Boy', reason: 'Confirmation arrived after extension limit', outcome: '+82% from watch price', review: 'Tighten early scout rule' },
  { token: 'Odogwu', reason: 'Holder growth data arrived late', outcome: '+36% in 10m', review: 'Provider latency review' }
];
const trades = [
  { token: 'Sabi Cat', amount: '₦10,000', pnl: '+₦3,184', entry: 'Score 86 + healthy curve', exit: 'TP1 and trailing stop', status: 'CLOSED' },
  { token: 'Naija Frog', amount: '₦7,500', pnl: '+₦1,420', entry: 'Scout entry at score 82', exit: '25% partial secured', status: 'OPEN' }
];

export default function BotScreen() {
  const [settings, setSettings] = useState(defaults);
  const [message, setMessage] = useState('');
  const [section, setSection] = useState<'RADAR' | 'TRADES' | 'MEMORY' | 'CONTROLS'>('RADAR');
  useEffect(() => { api<{ settings: Settings }>('/v1/bot/settings').then(r => setSettings(r.settings)).catch(() => {}); }, []);
  const save = async (next = settings) => { try { const r = await api<{ settings: Settings; message: string }>('/v1/bot/settings', { method: 'PUT', body: JSON.stringify(next) }); setSettings(r.settings); setMessage(r.message); } catch { setMessage('The backend could not save these controls.'); } };
  return <Page>
    <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><View><Text style={{ color: dark.text, fontSize: 28, fontWeight: '900' }}>Auto Sniper</Text><Text style={{ color: dark.muted, marginTop: 3 }}>Pump.fun intelligence radar</Text></View><View style={{ width: 12, height: 12, borderRadius: 6, backgroundColor: settings.active ? dark.green : dark.muted }} /></View>
    <ModePill />
    <LinearGradient colors={settings.active ? ['#124B37', '#101A16'] : ['#282217', '#15130E']} style={{ padding: 17, borderRadius: 18, borderWidth: 1, borderColor: settings.active ? '#287658' : '#594A23', gap: 13 }}>
      <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><View><Text style={{ color: settings.active ? dark.green : dark.yellow, fontSize: 11, fontWeight: '900' }}>{settings.active ? 'SCANNER RUNNING' : 'SCANNER STOPPED'}</Text><Text style={{ color: dark.text, fontSize: 21, fontWeight: '900', marginTop: 4 }}>{settings.active ? 'Watching the launch stream' : 'Ready for demo scanning'}</Text></View><Switch value={settings.active} onValueChange={(active) => save({ ...settings, active })} trackColor={{ true: dark.green }} /></View>
      <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><TopStat label="Last scan" value="4s ago" /><TopStat label="Scanned" value="1,284" /><TopStat label="Found" value="18" /><TopStat label="Blocked" value="47" /></View>
      <View style={{ height: 5, backgroundColor: '#24302B', borderRadius: 3 }}><View style={{ width: '31%', height: 5, backgroundColor: dark.yellow, borderRadius: 3 }} /></View>
      <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Text style={{ color: dark.muted, fontSize: 11 }}>Daily risk used</Text><Text style={{ color: dark.yellow, fontSize: 11, fontWeight: '900' }}>31% · ₦3,100 / ₦10,000</Text></View>
    </LinearGradient>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{(['RADAR', 'TRADES', 'MEMORY', 'CONTROLS'] as const).map(item => <Pressable key={item} onPress={() => setSection(item)} style={{ paddingHorizontal: 14, paddingVertical: 9, borderRadius: 99, backgroundColor: section === item ? dark.green : dark.surface }}><Text style={{ color: section === item ? '#06110D' : dark.muted, fontSize: 11, fontWeight: '900' }}>{item}</Text></Pressable>)}</ScrollView>
    {section === 'RADAR' && <Radar />}
    {section === 'TRADES' && <Trades />}
    {section === 'MEMORY' && <Memory />}
    {section === 'CONTROLS' && <Controls settings={settings} setSettings={setSettings} save={save} message={message} />}
  </Page>;
}

function Radar() { return <><SectionHeader title="Live scanner feed" action="DEMO STREAM" /><View style={{ backgroundColor: '#0B100E', borderRadius: 14, borderWidth: 1, borderColor: dark.border, paddingHorizontal: 14 }}>{logs.map((log, i) => <View key={log.time} style={{ flexDirection: 'row', gap: 10, paddingVertical: 12, borderBottomWidth: i === logs.length - 1 ? 0 : 1, borderBottomColor: dark.border }}><View style={{ alignItems: 'center' }}><View style={{ width: 9, height: 9, borderRadius: 5, backgroundColor: log.status === 'BLOCKED' ? dark.red : log.status === 'APPROVED' ? dark.green : dark.yellow }} />{i < logs.length - 1 && <View style={{ width: 1, flex: 1, backgroundColor: dark.border }} />}</View><View style={{ flex: 1 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Text style={{ color: dark.text, fontWeight: '900' }}>{log.token}</Text><Text style={{ color: dark.muted, fontSize: 10 }}>{log.time}</Text></View><Text style={{ color: log.status === 'BLOCKED' ? dark.red : dark.cyan, fontSize: 11, fontWeight: '800', marginTop: 3 }}>{log.signal} · {log.status}</Text><Text style={{ color: dark.muted, fontSize: 11, marginTop: 3 }}>{log.reason}</Text></View><Text style={{ color: dark.green, fontWeight: '900' }}>{log.score}</Text></View>)}</View>
  <SectionHeader title="Watching now" action="4 opportunities" />{demoTokens.map((token, i) => <View key={token.mint} style={{ padding: 14, borderRadius: 14, backgroundColor: dark.surface, borderWidth: 1, borderColor: dark.border, gap: 10 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><AssetIcon symbol={token.symbol} color={token.color} /><View style={{ flex: 1 }}><Text style={{ color: dark.text, fontWeight: '900' }}>{token.name}</Text><Pressable onPress={() => Clipboard.setStringAsync(token.mint)}><Text style={{ color: dark.cyan, fontSize: 10 }}>{token.mint.slice(0, 7)}…{token.mint.slice(-5)} · copy</Text></Pressable></View><Decision value={i === 2 ? 'BLOCKED' : i === 0 ? 'WATCH' : 'QUALIFY'} /></View><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><TopStat label="Runner" value={String(token.score)} /><TopStat label="Risk" value={String(token.risk)} /><TopStat label="Liquidity" value={token.liquidity} /><TopStat label="Holders" value={token.holders.toLocaleString()} /></View><Text style={{ color: dark.muted, fontSize: 11 }}>{i === 2 ? 'Blocked: wallet concentration and sell pressure rising.' : 'Watching: bonding curve and unique buyer growth still strengthening.'}</Text></View>)}
  <SectionHeader title="Bot intelligence" /><View style={{ padding: 15, borderRadius: 14, backgroundColor: '#151827', borderWidth: 1, borderColor: '#303657' }}><Text style={{ color: dark.purple, fontWeight: '900' }}>WHY THE BOT IS WAITING</Text><Text style={{ color: dark.text, lineHeight: 20, marginTop: 8 }}>Naija Frog gained 428 holders in 12 minutes and liquidity remains healthy. The engine wants one more confirmation from buy pressure before adding beyond the scout size.</Text></View></>; }
function Trades() { return <><View style={{ flexDirection: 'row', gap: 9 }}><Metric label="Today PnL" value="+₦4,604" color={dark.green} /><Metric label="7-day PnL" value="+₦18,420" color={dark.cyan} /><Metric label="Win rate" value="61.5%" color={dark.yellow} /></View><SectionHeader title="Bot trade history" />{trades.map(t => <View key={t.token} style={{ padding: 15, borderRadius: 14, backgroundColor: dark.surface, borderWidth: 1, borderColor: dark.border, gap: 8 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Text style={{ color: dark.text, fontSize: 16, fontWeight: '900' }}>{t.token}</Text><Text style={{ color: dark.green, fontWeight: '900' }}>{t.pnl}</Text></View><Text style={{ color: dark.muted, fontSize: 11 }}>{t.amount} · {t.status}</Text><Reason label="Entry" text={t.entry} /><Reason label="Exit" text={t.exit} /></View>)}<SectionHeader title="Performance detail" /><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 9 }}><Metric label="Average gain" value="+24.6%" color={dark.green} /><Metric label="Average loss" value="-8.1%" color={dark.red} /><Metric label="Best trade" value="+68.4%" color={dark.green} /><Metric label="Worst trade" value="-11.7%" color={dark.red} /><Metric label="Scans" value="8,921" color={dark.cyan} /><Metric label="Trades" value="26" color={dark.yellow} /></View></>; }
function Memory() { return <><SectionHeader title="Blocked-trade memory" action="Learning review" />{blocked.map(x => <View key={x.token} style={{ padding: 14, borderRadius: 14, backgroundColor: dark.surface, borderLeftWidth: 3, borderLeftColor: x.color, gap: 6 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><Text style={{ color: dark.text, fontWeight: '900' }}>{x.token}</Text><Text style={{ color: x.color, fontSize: 11, fontWeight: '900' }}>{x.quality}</Text></View><Text style={{ color: dark.red, fontSize: 11 }}>Blocked · {x.reason}</Text><Text style={{ color: dark.muted, fontSize: 11 }}>{x.outcome}</Text></View>)}<SectionHeader title="Missed opportunities" />{missed.map(x => <View key={x.token} style={{ padding: 14, borderRadius: 14, backgroundColor: '#1B1810', borderWidth: 1, borderColor: '#4B4024', gap: 5 }}><Text style={{ color: dark.text, fontWeight: '900' }}>{x.token} · <Text style={{ color: dark.yellow }}>{x.outcome}</Text></Text><Text style={{ color: dark.muted, fontSize: 11 }}>Missed: {x.reason}</Text><Text style={{ color: dark.cyan, fontSize: 11 }}>Review: {x.review}</Text></View>)}</>; }
function Controls({ settings, setSettings, save, message }: { settings: Settings; setSettings: (s: Settings) => void; save: (s?: Settings) => void; message: string }) { return <View style={{ padding: 16, borderRadius: 14, backgroundColor: dark.surface, borderWidth: 1, borderColor: dark.border, gap: 13 }}><SectionHeader title="Risk controls" /><Text style={{ color: dark.muted, fontSize: 11 }}>Execution mode</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 7 }}>{(['SIMULATION', 'MANUAL', 'SEMI_AUTO', 'FULL_AUTO'] as const).map(x => <Pressable onPress={() => setSettings({ ...settings, automationMode: x })} key={x} style={{ paddingHorizontal: 11, paddingVertical: 9, borderRadius: 8, backgroundColor: settings.automationMode === x ? dark.cyan : dark.surfaceRaised }}><Text style={{ color: settings.automationMode === x ? '#06110D' : dark.muted, fontSize: 9, fontWeight: '900' }}>{x.replace('_', ' ')}</Text></Pressable>)}</ScrollView><View style={{ flexDirection: 'row', gap: 8 }}>{(['SAFE', 'BALANCED', 'SNIPER'] as const).map(x => <Text onPress={() => setSettings({ ...settings, riskLevel: x })} key={x} style={{ flex: 1, textAlign: 'center', paddingVertical: 10, borderRadius: 8, color: settings.riskLevel === x ? '#06110D' : dark.muted, backgroundColor: settings.riskLevel === x ? dark.green : dark.surfaceRaised, fontSize: 10, fontWeight: '900' }}>{x}</Text>)}</View><Field label="Max trade amount" suffix="₦" value={settings.maxTradeNgn} set={v => setSettings({ ...settings, maxTradeNgn: v })} /><Field label="Take profit" suffix="%" value={settings.takeProfitPercent} set={v => setSettings({ ...settings, takeProfitPercent: v })} /><Field label="Stop loss" suffix="%" value={settings.stopLossPercent} set={v => setSettings({ ...settings, stopLossPercent: v })} /><Field label="Daily loss limit" suffix="%" value={settings.dailyLossLimitPercent} set={v => setSettings({ ...settings, dailyLossLimitPercent: v })} /><Field label="Max open trades" suffix="" value={settings.maxOpenTrades} set={v => setSettings({ ...settings, maxOpenTrades: v })} /><Field label="Max slippage" suffix="%" value={settings.maxSlippagePercent} set={v => setSettings({ ...settings, maxSlippagePercent: v })} /><Field label="Minimum liquidity" suffix="₦" value={settings.minimumLiquidityNgn} set={v => setSettings({ ...settings, minimumLiquidityNgn: v })} />{['Rug protection', 'Whale protection', 'Liquidity protection'].map(x => <View key={x} style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><Text style={{ color: dark.text }}>{x}</Text><Switch value disabled trackColor={{ true: dark.green }} /></View>)}{message ? <Text style={{ color: dark.green, fontSize: 11 }}>{message}</Text> : null}<Button title="Save protection rules" onPress={() => save()} /><Button title="Emergency stop" kind="danger" onPress={() => save({ ...settings, active: false })} /></View>; }
function TopStat({ label, value }: { label: string; value: string }) { return <View><Text style={{ color: dark.muted, fontSize: 9 }}>{label}</Text><Text numberOfLines={1} style={{ color: dark.text, fontWeight: '900', marginTop: 3 }}>{value}</Text></View>; }
function Decision({ value }: { value: string }) { const color = value === 'BLOCKED' ? dark.red : value === 'WATCH' ? dark.yellow : dark.green; return <View style={{ backgroundColor: `${color}18`, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 99 }}><Text style={{ color, fontSize: 9, fontWeight: '900' }}>{value}</Text></View>; }
function Reason({ label, text }: { label: string; text: string }) { return <Text style={{ color: dark.muted, fontSize: 11 }}><Text style={{ color: dark.cyan, fontWeight: '800' }}>{label}: </Text>{text}</Text>; }
function Field({ label, suffix, value, set }: { label: string; suffix: string; value: number; set: (n: number) => void }) { return <View style={{ flexDirection: 'row', alignItems: 'center', paddingVertical: 7, borderTopWidth: 1, borderTopColor: dark.border }}><Text style={{ color: dark.text, flex: 1 }}>{label}</Text><Text style={{ color: dark.muted }}>{suffix}</Text><TextInput value={String(value)} onChangeText={x => set(Number(x) || 0)} keyboardType="number-pad" style={{ color: dark.text, minWidth: 68, textAlign: 'right', fontWeight: '900', padding: 8 }} /></View>; }
function Metric({ label, value, color }: { label: string; value: string; color: string }) { return <View style={{ flexGrow: 1, flexBasis: '29%', padding: 12, borderRadius: 10, backgroundColor: dark.surface }}><Text style={{ color: dark.muted, fontSize: 9 }}>{label}</Text><Text adjustsFontSizeToFit numberOfLines={1} style={{ color, fontWeight: '900', marginTop: 5 }}>{value}</Text></View>; }
