import { useState } from 'react';
import { Pressable, Switch, Text, TextInput, View } from 'react-native';
import { Button, ModePill, Page, SectionHeader } from '@/components';
import { providerGroups } from '@/demo';
import { dark } from '@/theme';
export default function AdminScreen() {
  const [open, setOpen] = useState(''); const [message, setMessage] = useState('');
  return <Page><View><Text style={{ color: dark.red, fontSize: 11, fontWeight: '900' }}>ADMIN ACCESS</Text><Text style={{ color: dark.text, fontSize: 28, fontWeight: '900', marginTop: 3 }}>Business operations</Text></View><ModePill />
    <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 9 }}><Metric label="Users" value="3" /><Metric label="Pending KYC" value="1" /><Metric label="Deposits today" value="₦50K" /><Metric label="Risk alerts" value="2" /></View>
    <SectionHeader title="Operations" />{['Users & KYC', 'Deposits', 'Withdrawals', 'Trades', 'Tokens & risk', 'Bounties', 'Fees & limits', 'Audit log'].map(x => <Pressable key={x} onPress={() => setMessage(`${x} is managed in the full web admin. Mobile approvals unlock after admin MFA is configured.`)} style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: dark.border }}><Text style={{ color: dark.text, fontWeight: '700' }}>{x}</Text><Text style={{ color: dark.green }}>Review ›</Text></Pressable>)}
    <SectionHeader title="Providers & API keys" action="Server-side only" />{providerGroups.map(group => <View key={group.title} style={{ padding: 14, borderRadius: 12, backgroundColor: dark.surface, borderWidth: 1, borderColor: dark.border, gap: 8 }}><Pressable onPress={() => setOpen(open === group.title ? '' : group.title)} style={{ flexDirection: 'row', justifyContent: 'space-between' }}><View style={{ flex: 1 }}><Text style={{ color: dark.text, fontWeight: '900' }}>{group.title}</Text><Text style={{ color: dark.muted, fontSize: 11, marginTop: 3 }}>{group.names}</Text></View><Text style={{ color: dark.yellow, fontSize: 10 }}>{group.status}</Text></Pressable>{open === group.title && <><Text style={{ color: dark.muted, fontSize: 11 }}>{group.fields}</Text><TextInput secureTextEntry placeholder="Paste server credential" placeholderTextColor={dark.muted} style={{ minHeight: 46, borderRadius: 8, borderWidth: 1, borderColor: dark.border, backgroundColor: dark.surfaceRaised, color: dark.text, paddingHorizontal: 12 }} /><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><Text style={{ color: dark.text }}>Enabled as primary</Text><Switch value={false} /></View><Button title="Validate configuration" kind="secondary" onPress={() => setMessage('Credential was not stored. Connect the audited server secret manager first.')} /></>}</View>)}
    {message ? <Text style={{ color: dark.yellow, lineHeight: 18 }}>{message}</Text> : null}<SectionHeader title="Launch controls" /><Button title="Emergency pause all live actions" kind="danger" onPress={() => setMessage('Pause request recorded. Demo mode remains available.')} />
  </Page>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={{ flexBasis: '47%', flexGrow: 1, padding: 13, backgroundColor: dark.surface, borderRadius: 10 }}><Text style={{ color: dark.muted, fontSize: 10 }}>{label}</Text><Text style={{ color: dark.text, fontSize: 20, fontWeight: '900', marginTop: 4 }}>{value}</Text></View>; }
