import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { AssetIcon, Button, ModePill, Page, SectionHeader } from '@/components';
import { demoPosts } from '@/demo';
import { dark } from '@/theme';
const leaders = [{ name: 'Tobi Charts', roi: '+184%', rank: 'Legend' }, { name: 'Amina Alpha', roi: '+126%', rank: 'Whale' }, { name: 'Kola Onchain', roi: '+89%', rank: 'Elite' }];
export default function NetworkScreen() {
  const [followed, setFollowed] = useState<string[]>([]);
  const [message, setMessage] = useState('');
  return <Page><View><Text style={{ color: dark.text, fontSize: 28, fontWeight: '900' }}>Meme Network</Text><Text style={{ color: dark.muted, marginTop: 4 }}>Verified traders, communities, and onchain ideas.</Text></View><ModePill />
    <SectionHeader title="Top traders" action="Leaderboard" /> <View style={{ flexDirection: 'row', gap: 9 }}>{leaders.map((x, i) => <View key={x.name} style={{ flex: 1, padding: 11, borderRadius: 12, backgroundColor: dark.surface, borderWidth: 1, borderColor: dark.border }}><AssetIcon symbol={x.name} color={i === 0 ? dark.yellow : i === 1 ? dark.purple : dark.cyan} size={36} /><Text numberOfLines={1} style={{ color: dark.text, fontWeight: '900', marginTop: 8 }}>{x.name}</Text><Text style={{ color: dark.green, fontWeight: '900', marginTop: 4 }}>{x.roi}</Text><Text style={{ color: dark.muted, fontSize: 9 }}>{x.rank}</Text></View>)}</View>
    <SectionHeader title="For you" />{demoPosts.map(post => <View key={post.handle} style={{ padding: 15, borderRadius: 14, backgroundColor: dark.surface, borderWidth: 1, borderColor: dark.border, gap: 10 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><AssetIcon symbol={post.name} color={dark.purple} /><View style={{ flex: 1 }}><Text style={{ color: dark.text, fontWeight: '900' }}>{post.name} <Text style={{ color: dark.green }}>✓</Text></Text><Text style={{ color: dark.muted, fontSize: 10 }}>{post.handle} · {post.rank}</Text></View><Pressable onPress={() => setFollowed(v => v.includes(post.handle) ? v.filter(x => x !== post.handle) : [...v, post.handle])}><Text style={{ color: dark.green, fontWeight: '900' }}>{followed.includes(post.handle) ? 'Following' : 'Follow'}</Text></Pressable></View><Text style={{ color: dark.text, lineHeight: 20 }}>{post.body}</Text><View style={{ padding: 12, borderRadius: 10, backgroundColor: dark.surfaceRaised, flexDirection: 'row', justifyContent: 'space-between' }}><Text style={{ color: dark.muted }}>Verified trade return</Text><Text style={{ color: dark.green, fontWeight: '900' }}>{post.returnText}</Text></View><Text style={{ color: dark.muted, fontSize: 11 }}>♡ {post.likes}    ◯ {post.comments}    Share</Text></View>)}
    <SectionHeader title="Token communities" /><Button title="Explore NFROG community" kind="secondary" onPress={() => setMessage('Community chat requires the moderation and messaging service. Demo posts above remain read-only.')} />{message ? <Text style={{ color: dark.yellow, fontSize: 11, lineHeight: 17 }}>{message}</Text> : null}
  </Page>;
}
